/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as MachinesSlugRouteImport } from './routes/machines.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesSlugRoute = MachinesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MachinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/machines': typeof MachinesRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/machines/$slug': typeof MachinesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/machines': typeof MachinesRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/machines/$slug': typeof MachinesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/machines': typeof MachinesRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/machines/$slug': typeof MachinesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/machines' | '/technology' | '/machines/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/machines' | '/technology' | '/machines/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/machines'
    | '/technology'
    | '/machines/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MachinesRoute: typeof MachinesRouteWithChildren
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$slug': {
      id: '/machines/$slug'
      path: '/$slug'
      fullPath: '/machines/$slug'
      preLoaderRoute: typeof MachinesSlugRouteImport
      parentRoute: typeof MachinesRoute
    }
  }
}

interface MachinesRouteChildren {
  MachinesSlugRoute: typeof MachinesSlugRoute
}

const MachinesRouteChildren: MachinesRouteChildren = {
  MachinesSlugRoute: MachinesSlugRoute,
}

const MachinesRouteWithChildren = MachinesRoute._addFileChildren(
  MachinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MachinesRoute: MachinesRouteWithChildren,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
